POST http://localhost:5000/master/mesin
Content-Type: application/json

{
  "namaMesin": "Hosokawa Alphines"
}

###

GET http://localhost:5000/master/mesin

###
GET http://localhost:5000/master/mesin/0efe9037-b133-47a0-a9c1-fdaed69cdd68