POST http://localhost:5000/pengguna/daftar
Content-Type: application/json

{
  "username": "adminssff",
  "password": "rahasia",
  "namaLengkap": "Dzikri Nur Akbar",
  "namaIbuKandung": "Hawa"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "khalidsa",
  "password": "rahasiah"
}